### PR TITLE
upgrade to rust 2018 edition

### PR DESCRIPTION
**Pull request by ufoscout**
This PR:
- upgrades the code to rust 2018 edition
- revamps the project structure to a cargo workspace
- fixes a failing test in jmespath-cli
- fixes all clippy warnings
- updates all dependencies
- modifies the Variable::Number to use a serde_json::Number instead of a f64 to mimic the same behavior of serde itself. This permits to use, whenever possible, u64 or i64 instead of f64
- modifies the benches to run on stable (no need any more for a nightly compiler to run `cargo bench`)
- replaces many `.unwrap()` calls with code that returns a `Result` to avoid panics when serde_json is not able to serialize/deserialize

In addition, this PR removes the `jmespath-macro` crate as it does not compile any more with the current nightly compiler and I was not able to fix it.

### CODE REVIEW

**Comment by ufoscout** [comment]
@jamesls @mtdowling 
Please let me know if there is any interest in this PR. I will release my own version otherwise.

**Comment by ufoscout** [comment]
For anyone interested in this, I published in cargo.io the fixes of this PR under the name **jmespatch**.

Cargo.toml:
```toml
jmespatch = "0.3.0"
```

**Comment by liamdawson** [comment]
@ufoscout May I recommend you convert from a fork to a standalone repo? That way, if necessary, people can open issues etc. against your `jmespatch` crate.

**Comment by cetra3** [comment]
Hey, @ufoscout do you mind if I close this PR and we break out your changes to make them a bit easier to review?

**Comment by ufoscout** [comment]
Hi @cetra3, happy to know there's a new mantainer!
I am not sure how you can break out the changes of this PR, anyway, proceed as you wish.

**Comment by pratikpparikh** [comment]
@ufoscout is it possible to add WASM support to your library?

https://rustwasm.github.io/book/reference/add-wasm-support-to-crate.html

**Comment by ufoscout** [comment]
@pratikpparikh this is out of the scope of this PR.
If you are interested in it, I suggest that you open a dedicated issue.

**Comment by pratikpparikh** [comment]
@ufoscout #38 has been logged requesting WASM support.

**Comment by cetra3** [comment]
@ufoscout,

I'd like to ensure the `jmespath-macro` crate is workable.  I understand it may be a hard ask to do that in this PR, but at the very least it should not be removed.

**Comment by cetra3** [comment]
@ufoscout let me know your appetite of doing this or whether someone else needs to take over.

**Comment by ufoscout** [comment]
@cetra3 sorry for the confusion, but I understood you were going to close this one in favour of something else:

> Hey, @ufoscout do you mind if I close this PR and we break out your changes to make them a bit easier to review?


As I said before, the macro failed to compile with both rust stable and nightly. I am not an expert in macros, I tried to fix it and I gave up after some failures; so, I am not going to perform other attempts. 

Anyway, looking at the numbers in crates.io, it seems to me there's not much interest in the jmespath-macros crate.

**Comment by chipsenkbeil** [comment]
@cetra3 would it make sense to merge this with the intention of adding back in  the macros crate? You'll have a git history for the macros crate to see what it was, but this way the larger PR won't be sitting around and other contributions could be added.

There's an ast in the codebase from what I can see. When I wrote [vimwiki_macros](https://github.com/chipsenkbeil/vimwiki-rs/tree/master/vimwiki_macros), I used my parser to build an ast from within the macro and then had implemented a tokenize trait on all parts of the ast so I could convert the ast to a token stream. Could look into doing that here, but don't want to add it to a PR that's been sitting for over a year.

**Comment by cetra3** [comment]
Sure, let's merge it and work together to add the macros back!

**Comment by chipsenkbeil** [comment]
> Sure, let's merge it and work together to add the macros back!

Great! I'll take a look this weekend if I have time. Looks like this project is using an old Travis config for testing. Will either need to be moved to new Travis site or switch over to another provider like github actions

**Pull request merged**
